version: '2' # specify docker-compose version
# Define the services/containers to be run
services:
  frontend: #name of the first service
    build: clientKnightChallenge # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    container_name: front-container
    restart: always
  backend: #name of the second service
    build: serverKnightChallenge # specify the directory of the Dockerfile
    ports:
      - "8080:8080" #specify ports forewarding
    container_name: back-container
    restart: always
